name: Push 
on:  
  push: 
    paths: 
      - '.github/workflows/blank.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Fail script
      run: |
        .github/bin/fail-script.ps1 > .github/bin/fail.log
    
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: logs
        # A file, directory or wildcard pattern that describes what to upload
        path: .github/bin/fail.log
