name: Push 
on:  
  push: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: set output
      id: set
      run: |
         echo ::set-output name=json_var::'{ "event_type": "test", "client_payload": "111" }'
    
    - name: use output
      run: 
        echo $input
        echo $input.event_type
    
      env:
        input: ${{ steps.set.outputs.json_var }}
    
    #- uses: actions/checkout@v2
    - name: Create local changes
      if: 1!=1
      run: |
        cat > sales661.txt
    - name: Commit files
      if: 1!=1
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        git commit -m "Add changes" -a
        git tag v5.1
        git push origin v5.1

     
    #- name: Push changes
    #  uses: Woile/github-push-action@master
    #  with:
    #    github_token: ${{ secrets.GPR_ACCESS_TOKEN }}
    #   tags: "true"
