name: Push 
on:  issues

jobs:
  build:
    #if: startsWith(github.event.head_commit.message, 'Finally Merge')
    runs-on: ubuntu-latest
    steps:
      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v1


    - name: Create local changes
      run: |
        cat > sales123.txt
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all
        git commit -m "Add changes" -a
        git tag new2
    
    - name: Push changes
      uses: Woile/github-push-action@master
      with:
        github_token: ${{ secrets.GPR_ACCESS_TOKEN }}
        tags: "true"
