name: CI
on: 
  push:
    tags:
      - v1.*
  issue_comment:
    types: [created, deleted]
  pull_request_review_comment:
    types: [created, deleted]


   
  
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v1

    - name: Run a one-line script 

      run: echo Hello, world!

    - name: Run a multi-line script 

      run: |

        echo Add other actions to build,

        echo test, and deploy your project.
