name: create zip 
on: 
  push: 
    
jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - run:  mkdir frontend-zip
    - uses: montudor/action-zip@v0.1.0
      with:
         args: zip -qq -r ./frontend-zip/frontend.zip ./projects/frontend/
    - uses: actions/upload-artifact@master
      with:
          name: frontend
          path: ./frontend-zip
