name: create zip 
on: 
  push: 
    
jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - uses: montudor/action-zip@v0.1.0
      with:
         args: zip -qq ./projects/frontend/frontend.zip -d ./projects/frontend/
    - uses: actions/upload-artifact@master
      with:
          name: frontend
          path: ./projects/frontend/
