on: push


jobs:
  version:
    runs-on: ubuntu-latest
    name: get version
    steps:
    - name: get version
      run:  |
        echo $RELEASE_VERSION
        echo ${RELEASE_VERSION:11}
      env:
        RELEASE_VERSION: ${{ github.ref }}

