on: push


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run:  |
        echo ${GITHUB_REF:11}
        echo "::set-env name=RELEASE_VERSION::${GITHUB_REF:11}"
    - run: echo $RELEASE_VERSION
  job2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run:  |
        abc hhh
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: drop2
        path: new1.txt
  job3:
    if: always()
    runs-on: [ubuntu-latest]
    needs: [job1, job2]
    steps:
      - run:  curl -sSL https://api.github.com/repos/zhuOrg/orgrepo1/actions/runs/$run_id/jobs > jq &&             chmod +x jq
        env:
          run_id: ${{ github.run_id }} 
      - uses: actions/download-artifact@v1
        with:
          name: drop2
       
