on: push


jobs:
  version:
    runs-on: ubuntu-latest
    name: get version
    steps:
    - name: get version
      run:  |
        echo ${REF:11}
        echo "::set-output name=RELEASE_VERSION::${REF:11}"
      env:
        REF: ${{ github.ref }}
    - run: echo $RELEASE_VERSION
