name: Upload Website

on:
  push:
    branches:
    - master
env: 
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@v0.5.1

