name: test secrets
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: |
          echo "$GITHUB_CONTEXT"
          echo $GITHUB_REPOSITORY

     - name: update deploy status
       if: failure()
       uses: unacast/actions-github-deployment-status@0.2
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         status: ${{ job.status }}
