name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node13.6.0-chrome80-ff72
      options: --user 1001
    steps:
      # help us who how we are running in the container
      - uses: actions/checkout@v2
      - run: id
      - run: google-chrome --version
      - run: firefox --version


