name: CI
on: deployment
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT"

     - name: update deploy status
       if: always()
       uses: unacast/actions-github-deployment-status@0.2
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         status: ${{ job.status }}
