name: CI
on: deployment
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # help us who how we are running in the container
      - run: whoami
      - run: id
      - run: google-chrome --version
      - run: firefox --version



