name: test secrets
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: |
          echo "$GITHUB_CONTEXT"
          echo $GITHUB_REPOSITORY

     - name: Update release
       uses: johnwbyrd/update-release@v1.0.0
       with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./1.0.0.zip .github/workflows/prerelease.yml
          tag: '1.0.0'
