name: test secrets
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: |
          echo "$GITHUB_CONTEXT"
          echo $GITHUB_REPOSITORY

     - name: Update release
       uses: johnwbyrd/update-release@v1
       with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset: ./the-file-you-want-to-release.zip
          tag: '1.0.0'
