name: Upload Release
on: 
 check_suite:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2 
       - run: echo $EVENT
         env: 
           EVENT: ${{ tojson(github.event) }} 
       - uses: rjstone/discord-webhook-notify@v1
         with:
           severity: warn
           details: Test !
           description: '${{ github.event.release.name }} and ${{ github.event.release.body }}' 
           webhookUrl:  ${{ secrets.DISCORD_WEBHOOK }}
    
