name: Upload Release
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2 
       - uses: actions/upload-artifact@v1.0.0
         with: 
           name: drop
           path: projects/frontend/
  download:
     runs-on: ubuntu-latest
     steps: 
       - uses: actions/download-artifact@v1.0.0
         with:
           name: drop
  
    
