name: publish artifacts
on: 
  release:
     types: [published]
jobs:
  build:
    if: "!github.event.release.prerelease" 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - run: |
          echo $pre_release
          echo hello
          echo $login
          echo hello
          echo $GIT_CONTEXT
        env: 
          GIT_CONTEXT: ${{ tojson(github) }}
          pre_release: ${{ github.event.release.prerelease }}
          login: ${{ github.event.release.created_at}}
    
