name: Upload Release
on: 
  release:
     types: [published]
jobs:
  build:
    if: "!github.event.release.prerelease" 
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          echo $pre_release
          echo hello
          echo $login
          echo hello
          echo $GIT_CONTEXT
      env: 
          GIT_CONTEXT: ${{ tojson(github) }}
          pre_release: ${{ github.event.release.prerelease }}
          login: ${{ github.event.release.created_at}}
    
