name: publish artifacts
on: 
  release:
     types: [published]
jobs:
  build:
    if: "github.release.prerelease != 'true' "
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - run: |
          echo $GIT_CONTEXT
        env: 
          GIT_CONTEXT: ${{ tojson(github) }}
    
