# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  check_suite:

jobs:
  getchange:
   outputs:
      matrix: ${{ steps.changes.outputs.matrix }}
   runs-on: ubuntu-latest
   steps:
     - id: changes
       ## set matrix value based on file changes
       run: | 
         
         echo "::set-output name=matrix::{\"include\":[{\"python\":\"3.5\" },{\"python\":\"3.7\"}]}"
  build:
    needs: [getchange]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.getchange.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
   
