name: test matrix 
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-latest]
        TARGET: [x86_64-apple-darwin, armv7-unknown-linux-musleabihf, x86_64-unknown-linux-musl]
        COMPILER: [clang, arm-linux-gnueabihf-gcc-5, gcc]
        LINKER: [clang, gcc-5-arm-linux-gnueabihf, gcc]
        include: 
        - os: macos-latest
          TARGET: x86_64-apple-darwin
          COMPILER: clang
          LINKER: clang
          
        
    steps:
     - uses: actions/checkout@v1
        
